# Generated by Django 5.1.3 on 2025-02-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='Produtos relacionados'),
        ),
    ]
